// Generated by gencpp from file pepper_nodes/WakeUp.msg
// DO NOT EDIT!


#ifndef PEPPER_NODES_MESSAGE_WAKEUP_H
#define PEPPER_NODES_MESSAGE_WAKEUP_H

#include <ros/service_traits.h>


#include <pepper_nodes/WakeUpRequest.h>
#include <pepper_nodes/WakeUpResponse.h>


namespace pepper_nodes
{

struct WakeUp
{

typedef WakeUpRequest Request;
typedef WakeUpResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WakeUp
} // namespace pepper_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_nodes::WakeUp > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::pepper_nodes::WakeUp&) { return value(); }
};

template<>
struct DataType< ::pepper_nodes::WakeUp > {
  static const char* value()
  {
    return "pepper_nodes/WakeUp";
  }

  static const char* value(const ::pepper_nodes::WakeUp&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_nodes::WakeUpRequest> should match
// service_traits::MD5Sum< ::pepper_nodes::WakeUp >
template<>
struct MD5Sum< ::pepper_nodes::WakeUpRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_nodes::WakeUp >::value();
  }
  static const char* value(const ::pepper_nodes::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_nodes::WakeUpRequest> should match
// service_traits::DataType< ::pepper_nodes::WakeUp >
template<>
struct DataType< ::pepper_nodes::WakeUpRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_nodes::WakeUp >::value();
  }
  static const char* value(const ::pepper_nodes::WakeUpRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_nodes::WakeUpResponse> should match
// service_traits::MD5Sum< ::pepper_nodes::WakeUp >
template<>
struct MD5Sum< ::pepper_nodes::WakeUpResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_nodes::WakeUp >::value();
  }
  static const char* value(const ::pepper_nodes::WakeUpResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_nodes::WakeUpResponse> should match
// service_traits::DataType< ::pepper_nodes::WakeUp >
template<>
struct DataType< ::pepper_nodes::WakeUpResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_nodes::WakeUp >::value();
  }
  static const char* value(const ::pepper_nodes::WakeUpResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_NODES_MESSAGE_WAKEUP_H
