// Generated by gencpp from file rasa_ros/DialogueResponse.msg
// DO NOT EDIT!


#ifndef RASA_ROS_MESSAGE_DIALOGUERESPONSE_H
#define RASA_ROS_MESSAGE_DIALOGUERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rasa_ros
{
template <class ContainerAllocator>
struct DialogueResponse_
{
  typedef DialogueResponse_<ContainerAllocator> Type;

  DialogueResponse_()
    : answer()  {
    }
  DialogueResponse_(const ContainerAllocator& _alloc)
    : answer(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _answer_type;
  _answer_type answer;





  typedef boost::shared_ptr< ::rasa_ros::DialogueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rasa_ros::DialogueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DialogueResponse_

typedef ::rasa_ros::DialogueResponse_<std::allocator<void> > DialogueResponse;

typedef boost::shared_ptr< ::rasa_ros::DialogueResponse > DialogueResponsePtr;
typedef boost::shared_ptr< ::rasa_ros::DialogueResponse const> DialogueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rasa_ros::DialogueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rasa_ros::DialogueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::rasa_ros::DialogueResponse_<ContainerAllocator1> & lhs, const ::rasa_ros::DialogueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.answer == rhs.answer;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::rasa_ros::DialogueResponse_<ContainerAllocator1> & lhs, const ::rasa_ros::DialogueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace rasa_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rasa_ros::DialogueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rasa_ros::DialogueResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rasa_ros::DialogueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7e708f879c94bb931716d8f4f130f30";
  }

  static const char* value(const ::rasa_ros::DialogueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7e708f879c94bb9ULL;
  static const uint64_t static_value2 = 0x31716d8f4f130f30ULL;
};

template<class ContainerAllocator>
struct DataType< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rasa_ros/DialogueResponse";
  }

  static const char* value(const ::rasa_ros::DialogueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string answer\n"
;
  }

  static const char* value(const ::rasa_ros::DialogueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.answer);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DialogueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rasa_ros::DialogueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rasa_ros::DialogueResponse_<ContainerAllocator>& v)
  {
    s << indent << "answer: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.answer);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RASA_ROS_MESSAGE_DIALOGUERESPONSE_H
