(cl:defpackage pepper_nodes-srv
  (:use )
  (:export
   "EXECUTEJS"
   "<EXECUTEJS-REQUEST>"
   "EXECUTEJS-REQUEST"
   "<EXECUTEJS-RESPONSE>"
   "EXECUTEJS-RESPONSE"
   "LOADURL"
   "<LOADURL-REQUEST>"
   "LOADURL-REQUEST"
   "<LOADURL-RESPONSE>"
   "LOADURL-RESPONSE"
   "TEXT2SPEECH"
   "<TEXT2SPEECH-REQUEST>"
   "TEXT2SPEECH-REQUEST"
   "<TEXT2SPEECH-RESPONSE>"
   "TEXT2SPEECH-RESPONSE"
  ))

