language: it

pipeline:
#Pipeline used to train model.
  - name: SpacyNLP
    model: "it_core_news_md"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
  - name: EntitySynonymMapper
  - name: SklearnIntentClassifier
  #- name: ResponseSelector
  #  epochs: 100
  #  constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.3
    ambiguity_threshold: 0.1
# Configuration for Rasa Core.
policies:
# Policies used to train model.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
